# Generated by Django 5.2.7 on 2025-10-23 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('monthly_payment', models.PositiveIntegerField(default=0, verbose_name="Oylik to‘lov miqdori (so'm)")),
                ('default_monthly_payment', models.PositiveIntegerField(default=1, help_text='Shartnomaga asosan boshlang‘ich oylik to‘lov (so‘mda)')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dormitories', to='accounts.director')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('entrance', models.BooleanField(default=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='yotoqxona.dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('size', models.PositiveSmallIntegerField()),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='yotoqxona.dormitory')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'unique_together': {('dormitory', 'number')},
            },
        ),
    ]
