# Generated by Django 5.2.7 on 2025-10-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('yotoqxona', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='yotoqxona.dormitory'),
        ),
    ]
